server:
  port: 8082

spring:
  application:
    name: match-service
  datasource:
    url: jdbc:mysql://localhost:3306/exchange_lab?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
    username: exchange_lab
    password: exchange_lab
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    consumer:
      group-id: exchange-lab-order-matcher
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: dev.exchangelab.*
    listener:
      concurrency: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info
